server:
  port: 8088
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: data-micro
          uri: lb://DATA-MICRO
          predicates:
            - Path=/DATA-MICRO/**
        - id: mediator-micro-serv
          uri: lb:/MEDIATOR-MICRO-SERV
          predicates:
            - Path=/MEDIATOR-MICRO-SERV/**
        - id: web-scraping
          uri: lb://WEB-SCRAPING
          predicates:
            - Path=/WEB-SCRAPING/**