server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          default-label: master #rama en la que se trabaja
          uri: https://github.com/JuanPatinoGomez/web-scraping-pasaportes.git #url del repositorio
          search-paths: config-data
  application:
    name: config-service #nombre del servicio